baseurl = 'https://realzhangm.cn'
languageCode = 'zh-cn'
defaultContentLanguage = "zh"

title = 'zhangm blog'
author = "zhangm"
copyright = "Copyright © 2018–2022, zhangm; all rights reserved."

paginate = 5
enableInlineShortcodes = true

theme = "paper"

[params]
disableHLJS = false       # don't use highlight.js
github = 'realzhangm'     # github.com/YOUR_GITHUB_ID

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
